In [38]:
import numpy as np

In [91]:
a = np.arange(15).reshape(3, 5)

In [40]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
a.ndim

2

In [42]:
a.shape

(3, 5)

In [43]:
a.size

15

In [44]:
a.dtype.name

'int32'

In [45]:
a.data

In [46]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [47]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [48]:
b.ndim

2

In [49]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [50]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [51]:
c.ndim

2

In [52]:
d = np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
d.ndim

3

In [53]:
np.empty(2) 

array([-2.22696115e-069,  1.20161051e-228])

In [54]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [55]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [56]:
b.shape

(2, 3)

In [57]:
d

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [58]:
d.shape

(3, 2, 2)

In [59]:
a.size

15

In [60]:
a.dtype.name


'int32'

In [61]:
a.itemsize


4

In [62]:
a.data

In [63]:
a = np.array( [ 1, 2, 3 ])

In [64]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [65]:
print(array_example.ndim)
print(array_example.size)
print(array_example.shape)

3
24
(3, 2, 4)


In [111]:
rg = np.random.default_rng(1)
print(rg)
r=rg.random((3, 4))
print(r)

Generator(PCG64)
[[0.51182162 0.9504637  0.14415961 0.94864945]
 [0.31183145 0.42332645 0.82770259 0.40919914]
 [0.54959369 0.02755911 0.75351311 0.53814331]]


In [106]:
r2 = np.random.rand(3,4)
r2

array([[0.79013496, 0.81705574, 0.88035128, 0.56466768],
       [0.91849099, 0.76475945, 0.04421298, 0.95748273],
       [0.96686873, 0.64144916, 0.45036204, 0.94203048]])

In [113]:
a1 = np.floor(100 * r)
print(a1)

[[51. 95. 14. 94.]
 [31. 42. 82. 40.]
 [54.  2. 75. 53.]]


In [114]:
a2 = 100 * r
print(a2)

[[51.18216247 95.04636963 14.41596127 94.86494471]
 [31.1831452  42.3326449  82.77025938 40.91991364]
 [54.95936877  2.75591132 75.35131087 53.81433132]]


In [115]:
a3 = np.ceil(100 * r)
print(a3)

[[52. 96. 15. 95.]
 [32. 43. 83. 41.]
 [55.  3. 76. 54.]]


In [116]:
a4 = np.round(100 * r,1)
print(a4)

[[51.2 95.  14.4 94.9]
 [31.2 42.3 82.8 40.9]
 [55.   2.8 75.4 53.8]]


In [119]:
r2 = np.random.random(3)
r2

array([0.1409813 , 0.20463868, 0.43154285])

In [120]:
a.shape

(3, 5)

In [85]:
a.ravel()  # returns the array, flattened

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [86]:
a.reshape(6, 2) 

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [87]:
a.T  # returns the array, transposed

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [88]:
a.T.shape

(4, 3)

In [92]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])

In [94]:
axis_0 = np.concatenate((x,y),axis=0)

In [95]:
axis_0.ndim

2